apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo-app
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-container
          image: <image-url>
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: <datasource-url>
            - name: SPRING_DATASOURCE_USERNAME
              value: <username>
            - name: SPRING_DATASOURCE_PASSWORD
              value: <password>
